# Generated by Django 3.2.9 on 2021-11-28 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('correo', models.EmailField(max_length=254)),
                ('nombre', models.CharField(max_length=50)),
                ('deuda', models.BigIntegerField(default=0)),
                ('telefono', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=20)),
                ('contrasena', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('numero_tarjeta', models.IntegerField(primary_key=True, serialize=False)),
                ('codigo', models.ImageField(upload_to='')),
                ('habilitada', models.BooleanField()),
                ('dueño', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='appFuncionario.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('num_servicio', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_reserva_servicio', models.DateTimeField()),
                ('fecha_inicio_servicio', models.DateTimeField()),
                ('fecha_termino_servicio', models.DateTimeField()),
                ('Cliente', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='appFuncionario.cliente')),
                ('Funcionario', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='appFuncionario.funcionario')),
            ],
        ),
    ]
