# Generated by Django 3.2.9 on 2021-11-29 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appFuncionario', '0002_alter_servicio_num_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='Cliente',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='appFuncionario.cliente'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='fecha_inicio_servicio',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='fecha_reserva_servicio',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='fecha_termino_servicio',
            field=models.DateTimeField(null=True),
        ),
    ]
