# Generated by Django 3.2.9 on 2021-11-29 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appFuncionario', '0003_auto_20211128_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='Funcionario',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='appFuncionario.funcionario'),
        ),
    ]
