# Generated by Django 3.2.9 on 2021-11-29 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appFuncionario', '0005_auto_20211129_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarjeta',
            old_name='dueño',
            new_name='Dueno',
        ),
    ]
