# Generated by Django 3.2.9 on 2021-11-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFuncionario', '0006_rename_dueño_tarjeta_dueno'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='imagen',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
