# Generated by Django 3.2.9 on 2021-12-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFuncionario', '0012_alter_funcionario_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fotoPerfil',
            field=models.ImageField(default='funcionarios/userDefault.png', null=True, upload_to='clientes/'),
        ),
    ]
