# Generated by Django 3.2.9 on 2021-12-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFuncionario', '0014_servicio_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
