# Generated by Django 3.2.9 on 2021-12-13 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appFuncionario', '0015_alter_cliente_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=15, null=True)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_baja', models.DateField(null=True)),
                ('instrucciones', models.TextField(max_length=100)),
                ('desechable', models.BooleanField()),
                ('requiere_epp', models.BooleanField()),
                ('lista_epp_requerido', models.TextField(max_length=20, null=True)),
                ('descripcion_estado', models.TextField(max_length=50, null=True)),
                ('Funcionario', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='appFuncionario.funcionario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Estacionamiento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=15, null=True)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_baja', models.DateField(null=True)),
                ('numero_estacionamiento', models.CharField(max_length=10)),
                ('area', models.CharField(max_length=3, null=True)),
                ('disponibilidad', models.BooleanField()),
                ('Funcionario', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='appFuncionario.funcionario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EPP',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=15, null=True)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_baja', models.DateField(null=True)),
                ('talla', models.CharField(max_length=3, null=True)),
                ('desechable', models.BooleanField()),
                ('color', models.CharField(max_length=10, null=True)),
                ('Funcionario', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='appFuncionario.funcionario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bicicleta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=15, null=True)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_baja', models.DateField(null=True)),
                ('color', models.CharField(max_length=10)),
                ('observaciones', models.TextField(max_length=50, null=True)),
                ('accesorios', models.TextField(max_length=50, null=True)),
                ('activoFijo', models.BooleanField()),
                ('estado', models.TextField(max_length=20)),
                ('Funcionario', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='appFuncionario.funcionario')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
