# Generated by Django 3.2.9 on 2021-12-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFuncionario', '0016_auto_20211213_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herramienta',
            name='descripcion_estado',
        ),
        migrations.RemoveField(
            model_name='herramienta',
            name='lista_epp_requerido',
        ),
        migrations.AddField(
            model_name='herramienta',
            name='estado',
            field=models.CharField(blank=True, default='no especificado', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='herramienta',
            name='lista_epp',
            field=models.CharField(blank=True, default='no especificado', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='accesorios',
            field=models.CharField(blank=True, default='no especificado', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='estado',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='marca',
            field=models.CharField(blank=True, default='generico', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='observaciones',
            field=models.CharField(blank=True, default='no especificado', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='epp',
            name='color',
            field=models.CharField(blank=True, default='no especificado', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='epp',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='epp',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='epp',
            name='marca',
            field=models.CharField(blank=True, default='generico', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='epp',
            name='talla',
            field=models.CharField(blank=True, default='sin Talla', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='estacionamiento',
            name='area',
            field=models.CharField(blank=True, default='no especificado', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='estacionamiento',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estacionamiento',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estacionamiento',
            name='marca',
            field=models.CharField(blank=True, default='generico', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='instrucciones',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='marca',
            field=models.CharField(blank=True, default='generico', max_length=15, null=True),
        ),
    ]
