# Generated by Django 3.2.9 on 2021-12-17 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFuncionario', '0017_auto_20211214_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicicleta',
            name='accesorios',
            field=models.CharField(blank=True, default='No especificado', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='marca',
            field=models.CharField(blank=True, default='Generico', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='observaciones',
            field=models.CharField(blank=True, default='No especificado', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='epp',
            name='color',
            field=models.CharField(blank=True, default='No Especificado', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='epp',
            name='marca',
            field=models.CharField(blank=True, default='Generico', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='epp',
            name='talla',
            field=models.CharField(blank=True, default='sin Talla', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='estacionamiento',
            name='area',
            field=models.CharField(blank=True, default='', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='estacionamiento',
            name='marca',
            field=models.CharField(blank=True, default='Generico', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='estado',
            field=models.CharField(blank=True, default='No especificado', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='lista_epp',
            field=models.CharField(blank=True, default='No especificado', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='marca',
            field=models.CharField(blank=True, default='Generico', max_length=15, null=True),
        ),
    ]
