# Generated by Django 3.2.9 on 2021-12-20 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFuncionario', '0019_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='bicicleta',
            name='almacenado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='epp',
            name='almacenado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estacionamiento',
            name='almacenado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='herramienta',
            name='almacenado',
            field=models.BooleanField(default=False),
        ),
    ]
